/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package detailDataJtextField;

/**
 *
 * @author Deny Mariyono
 */
public class UserTR extends javax.swing.JFrame {

    /**
     * Creates new form UserTR
     */
    public UserTR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_kasir_form.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        nama_kasir_form.setText("Agung Kurniawan");
        jPanel1.add(nama_kasir_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Kasir Laundry");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 80, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("ID Kasir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));

        id_detail_kasir_form.setText("jLabel1");
        jPanel1.add(id_detail_kasir_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Alamat Kasir");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, 20));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setText("Nomor Telfon");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 20));

        alamat_kasir_form.setText("jLabel1");
        jPanel1.add(alamat_kasir_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 150, -1));

        nomor_telfon_kasir_form.setText("jLabel1");
        jPanel1.add(nomor_telfon_kasir_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 160, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconJoptionPane/phone-call (1).png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconJoptionPane/pin (1).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconJoptionPane/driver-license (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconJoptionPane/id-card.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 50));

        Username.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Username.setText("Username");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconJoptionPane/padlock.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, 50));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconJoptionPane/key.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, 50));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setText("Hak Akses");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, 20));

        username_kasir_detail_form.setText("jLabel2");
        jPanel1.add(username_kasir_detail_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 160, -1));

        password_detail_form.setText("jLabel2");
        jPanel1.add(password_detail_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 160, -1));

        hakakses_detail_form.setText("jLabel2");
        jPanel1.add(hakakses_detail_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageDashboard/Desktop - 22 (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserTR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Username;
    public static final javax.swing.JLabel alamat_kasir_form = new javax.swing.JLabel();
    public static final javax.swing.JLabel hakakses_detail_form = new javax.swing.JLabel();
    public static final javax.swing.JLabel id_detail_kasir_form = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel nama_kasir_form = new javax.swing.JLabel();
    public static final javax.swing.JLabel nomor_telfon_kasir_form = new javax.swing.JLabel();
    public static final javax.swing.JLabel password_detail_form = new javax.swing.JLabel();
    public static final javax.swing.JLabel username_kasir_detail_form = new javax.swing.JLabel();
    // End of variables declaration                   
}
